services:
  postgres:
    image: postgres:14-alpine
    container_name: offchainvm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: offchainvm
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: offchainvm-redis
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  coordinator:
    build:
      context: ./coordinator
      dockerfile: ../docker/Dockerfile.coordinator
    container_name: offchainvm-coordinator
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./coordinator/.env
    ports:
      - "${COORDINATOR_EXTERNAL_PORT:-8080}:8080"
    volumes:
      - wasm_cache:/var/offchainvm/wasm
    # Note: For keystore access from coordinator container:
    # - macOS/Windows: Use KEYSTORE_BASE_URL=http://host.docker.internal:8081
    # - Linux: Use KEYSTORE_BASE_URL=http://172.17.0.1:8081
    #   Linux also requires UFW firewall rule:
    #   sudo ufw allow from 172.16.0.0/12 to any port 8081 && sudo ufw reload

volumes:
  postgres_data:
  redis_data:
  wasm_cache:
