version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: offchainvm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: offchainvm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: offchainvm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  coordinator:
    build:
      context: ./coordinator
      dockerfile: ../docker/Dockerfile.coordinator
    container_name: offchainvm-coordinator
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres/offchainvm
      REDIS_URL: redis://redis:6379
      WASM_CACHE_DIR: /var/offchainvm/wasm
      REQUIRE_AUTH: "false"  # Disable auth in dev mode
      RUST_LOG: offchainvm_coordinator=debug
    ports:
      - "8080:8080"
    volumes:
      - wasm_cache:/var/offchainvm/wasm

volumes:
  postgres_data:
  redis_data:
  wasm_cache:
