#!/bin/bash
# ============================================================================
# Confidential Intents E2E Test — coordinator /wallet/v1/confidential/* routes
#
# Real-token end-to-end test of the confidential shard (Defuse confidential
# intents) THROUGH the coordinator, the confidential analog of
# wallet_intents_e2e.sh. Mirrors the live exploration scripts
# (/tmp/conf_e2e.py shield+withdraw, conf_solana.py cross-chain deposit,
# conf_sol_out.py cross-chain withdraw) but drives the coordinator REST API and
# asserts on settlement + confidential balance deltas.
#
# Phases:
#   setup           — register wallet OR reuse saved state.env; show address + prereqs
#   roundtrip       — SHIELD 0.01 wNEAR → assert settled + balance +amount →
#                     UNSHIELD → assert settled + balance back. THE real-token test.
#   shield          — SHIELD only (asserts settlement)
#   unshield        — UNSHIELD only (asserts settlement)
#   balance         — show confidential balances
#   deposit-intent  — cross-chain DEPOSIT quote (Solana → confidential; address only)
#   withdraw        — cross-chain WITHDRAW (asserts settlement)
#   status <id>     — poll a request to terminal status
#   show / reset    — print / nuke saved wallet state
#
# GATE: the live phases require ONECLICK_CONFIDENTIAL_JWT to be set;
# unset → SKIP (exit 0), so CI can run this unconditionally. The coordinator must
# also have ENABLE_CONFIDENTIAL_INTENTS + the confidential upstream configured
# (else routes return HTTP 503, which the script surfaces).
#
# PREREQ for roundtrip/shield: the wallet must already hold SHIELD_AMOUNT of
# SHIELD_TOKEN in its PUBLIC intents balance. Fund it first, e.g. via
# wallet_intents_e2e.sh (fund NEAR → wrap → POST /wallet/v1/intents/deposit).
#
# Usage:
#   ./tests/wallet_confidential_e2e.sh setup
#   ONECLICK_CONFIDENTIAL_JWT=1 ./tests/wallet_confidential_e2e.sh roundtrip
#   ONECLICK_CONFIDENTIAL_JWT=1 WITHDRAW_CHAIN=solana \
#     WITHDRAW_TO=<sol-addr> WITHDRAW_TOKEN=nep141:sol-…omft.near WITHDRAW_AMOUNT=500000 \
#     ./tests/wallet_confidential_e2e.sh withdraw
#
# Environment:
#   COORDINATOR_URL  — default http://localhost:8080
#   NETWORK          — testnet | mainnet (default: mainnet; confidential talks to mainnet intents.near)
#   WALLET_API_KEY   — override saved key (usually let setup save it)
#   SHIELD_TOKEN     — default nep141:wrap.near
#   SHIELD_AMOUNT    — default 10000000000000000000000 (0.01 wNEAR, 24 dec)
#   WITHDRAW_CHAIN   — destination chain (default: solana); chain=near is rejected (use unshield)
#   WITHDRAW_TO      — destination-chain recipient address
#   WITHDRAW_TOKEN   — confidential source asset to deliver (e.g. nep141:sol-…omft.near)
#   WITHDRAW_AMOUNT  — amount in minimal units
#   DEPOSIT_SOURCE_ASSET — defuse asset id to bridge in (default: Solana USDC omft)
#   DEPOSIT_AMOUNT   — amount in minimal units (default: 500000 = 0.5 USDC)
# ============================================================================

set -euo pipefail

COORDINATOR_URL="${COORDINATOR_URL:-http://localhost:8080}"
NETWORK="${NETWORK:-mainnet}"

SHIELD_TOKEN="${SHIELD_TOKEN:-nep141:wrap.near}"
SHIELD_AMOUNT="${SHIELD_AMOUNT:-10000000000000000000000}" # 0.01 wNEAR (24 decimals)

SOL_USDC="nep141:sol-5ce3bf3a31af18be40ba30f721101b4341690186.omft.near"
DEPOSIT_SOURCE_ASSET="${DEPOSIT_SOURCE_ASSET:-$SOL_USDC}"
DEPOSIT_AMOUNT="${DEPOSIT_AMOUNT:-500000}" # 0.5 USDC (6 decimals)

# ─── State persistence (shared convention with wallet_intents_e2e.sh) ────────
STATE_DIR="${OUTLAYER_E2E_STATE_DIR:-$HOME/.outlayer}"
STATE_FILE="${OUTLAYER_E2E_STATE_FILE:-$STATE_DIR/wallet_e2e_state.env}"

if [ -z "${WALLET_API_KEY:-}" ] && [ -f "$STATE_FILE" ]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    if [ -n "${WALLET_API_KEY:-}" ]; then
        echo "↻ loaded saved wallet from $STATE_FILE (wallet_id=${WALLET_ID:-?}, account=${NEAR_ADDRESS:-?})"
    fi
fi

save_state() {
    mkdir -p "$STATE_DIR"
    umask 077
    {
        echo "# Generated by wallet_confidential_e2e.sh / wallet_intents_e2e.sh setup — do not commit."
        echo "WALLET_API_KEY=${WALLET_API_KEY}"
        echo "WALLET_ID=${WALLET_ID:-}"
        echo "NEAR_ADDRESS=${NEAR_ADDRESS:-}"
        echo "COORDINATOR_URL=${COORDINATOR_URL}"
        echo "NETWORK=${NETWORK}"
        echo "SAVED_AT=$(date -u +%FT%TZ)"
    } > "$STATE_FILE"
    chmod 600 "$STATE_FILE"
}

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; NC='\033[0m'

# ============================================================================
# Helpers
# ============================================================================

curl_get() {
    curl -s -w "\n%{http_code}" -H "Authorization: Bearer $WALLET_API_KEY" "${COORDINATOR_URL}${1}"
}

curl_post() {
    local path="$1" body="$2" idem_key="${3:-}"
    local extra_headers=()
    [ -n "$idem_key" ] && extra_headers+=(-H "X-Idempotency-Key: $idem_key")
    curl -s -w "\n%{http_code}" -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $WALLET_API_KEY" \
        ${extra_headers[@]+"${extra_headers[@]}"} \
        -d "$body" "${COORDINATOR_URL}${path}"
}

parse_response() {
    RESP_BODY=$(echo "$1" | sed '$d')
    RESP_CODE=$(echo "$1" | tail -1)
}

check_coordinator() {
    if ! curl -s "${COORDINATOR_URL}/health" > /dev/null 2>&1; then
        echo -e "${RED}ERROR: Coordinator not running at ${COORDINATOR_URL}${NC}"; exit 1
    fi
}

require_confidential_enabled() {
    if [ -z "${ONECLICK_CONFIDENTIAL_JWT:-}" ]; then
        echo -e "${YELLOW}SKIP:${NC} ONECLICK_CONFIDENTIAL_JWT is not set — confidential e2e disabled."
        echo "      Set it (any value) to run the live confidential phases; the coordinator must"
        echo "      also have ENABLE_CONFIDENTIAL_INTENTS + the confidential upstream configured."
        exit 0
    fi
}

require_api_key() {
    WALLET_API_KEY="${WALLET_API_KEY:?No wallet API key — run '$0 setup' first (or set WALLET_API_KEY).}"
}

# Big-integer compare (24-dec amounts exceed bash/64-bit). Echoes -1 | 0 | 1.
bi_cmp() { python3 -c "import sys;a=int(sys.argv[1]);b=int(sys.argv[2]);print(0 if a==b else(1 if a>b else -1))" "$1" "$2"; }
bi_add() { python3 -c "import sys;print(int(sys.argv[1])+int(sys.argv[2]))" "$1" "$2"; }

# Confidential balance of one token ("0" if absent). Echoes the integer string.
cf_balance() {
    local token="$1" resp
    resp=$(curl_get "/wallet/v1/confidential/balance?token=$(printf '%s' "$token" | sed 's/:/%3A/g')")
    parse_response "$resp"
    [ "$RESP_CODE" = "200" ] || { echo -e "${RED}cf_balance HTTP $RESP_CODE: $RESP_BODY${NC}" >&2; return 1; }
    echo "$RESP_BODY" | jq -r '.balance // "0"'
}

# Public intents balance of one token (for the shield prereq). Echoes the integer.
public_intents_balance() {
    local token="$1" resp
    resp=$(curl_get "/wallet/v1/balance?source=intents&token=$(printf '%s' "$token" | sed 's/:/%3A/g')")
    parse_response "$resp"
    [ "$RESP_CODE" = "200" ] || { echo "0"; return 0; }
    echo "$RESP_BODY" | jq -r '.balance // "0"'
}

# Submit a confidential op; sets LAST_REQUEST_ID; hard-fails on non-200 / 503.
report_op() {
    echo -e "  HTTP $RESP_CODE"
    if [ "$RESP_CODE" = "503" ]; then
        echo -e "  ${YELLOW}503 confidential_unavailable${NC} — coordinator not configured for confidential intents."
        echo "  $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"; exit 1
    fi
    if [ "$RESP_CODE" != "200" ]; then
        echo -e "  ${RED}FAIL${NC}: $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"; exit 1
    fi
    echo "  $(echo "$RESP_BODY" | jq -c '.')"
    LAST_REQUEST_ID=$(echo "$RESP_BODY" | jq -r '.request_id // empty')
}

# Poll a request to terminal. Returns 0=success, 1=failed/refunded, 2=timeout.
#
# Bumped from 30 to 90 iterations (= ~3 min wall-clock) because UNSHIELD
# direction reliably moves the funds on-chain in seconds but its upstream
# /v0/status sometimes stays "processing" for >60 s before flipping to
# "success" — the solver fills `nearTxHashes` lazily for the unshield leg.
# Most ops settle in < 15 iterations; the headroom protects against the slow
# UNSHIELD path without slowing the fast ones.
poll_request() {
    local rid="$1" i status
    [ -n "$rid" ] || { echo -e "  ${YELLOW}no request_id to poll${NC}"; return 2; }
    echo -e "${CYAN}  polling request $rid …${NC}"
    for i in $(seq 1 90); do
        parse_response "$(curl_get "/wallet/v1/requests/$rid")"
        status=$(echo "$RESP_BODY" | jq -r '.status // "?"')
        echo "    [$i] status=$status"
        case "$status" in
            success) echo "    $(echo "$RESP_BODY" | jq -c '.result')"; return 0 ;;
            failed|refunded) echo -e "    ${RED}terminal: $status${NC} $(echo "$RESP_BODY" | jq -c '.result')"; return 1 ;;
        esac
        sleep 2
    done
    return 2
}

# Poll + hard-assert the op settled to success.
assert_settled() {
    local rid="$1" label="$2" rc
    set +e; poll_request "$rid"; rc=$?; set -e
    case "$rc" in
        0) echo -e "  ${GREEN}PASS${NC} $label settled (success)" ;;
        1) echo -e "  ${RED}FAIL${NC} $label settled to a terminal failure"; exit 1 ;;
        2) echo -e "  ${RED}FAIL${NC} $label did not settle within timeout (rid=$rid; re-check via: $0 status $rid)"; exit 1 ;;
    esac
}

ensure_address() {
    if [ -z "${NEAR_ADDRESS:-}" ]; then
        parse_response "$(curl_get "/wallet/v1/address?chain=near")"
        [ "$RESP_CODE" = "200" ] || { echo -e "${RED}get address HTTP $RESP_CODE${NC}: $RESP_BODY"; exit 1; }
        NEAR_ADDRESS=$(echo "$RESP_BODY" | jq -r '.address')
    fi
}

# ============================================================================
# Commands
# ============================================================================

cmd_setup() {
    echo -e "${CYAN}== Confidential E2E — Setup (network: $NETWORK) ==${NC}"
    check_coordinator
    if [ -z "${WALLET_API_KEY:-}" ]; then
        echo "Registering new wallet…"
        parse_response "$(curl -s -w "\n%{http_code}" -X POST "${COORDINATOR_URL}/register")"
        [ "$RESP_CODE" = "200" ] || { echo -e "${RED}register HTTP $RESP_CODE${NC}: $RESP_BODY"; exit 1; }
        WALLET_API_KEY=$(echo "$RESP_BODY" | jq -r '.api_key')
        WALLET_ID=$(echo "$RESP_BODY" | jq -r '.wallet_id')
        NEAR_ADDRESS=$(echo "$RESP_BODY" | jq -r '.near_account_id')
        save_state
        echo -e "Saved state to $STATE_FILE (chmod 600)."
    fi
    ensure_address
    echo -e "Wallet ID:    ${GREEN}${WALLET_ID:-?}${NC}"
    echo -e "NEAR address: ${GREEN}$NEAR_ADDRESS${NC}"
    echo ""
    echo "Prerequisite for roundtrip/shield:"
    echo "  $SHIELD_TOKEN must already be in your PUBLIC intents balance ≥ $SHIELD_AMOUNT."
    echo "  Fund via wallet_intents_e2e.sh: fund NEAR → wrap (/call) → POST /wallet/v1/intents/deposit."
}

# Self-contained real-token assertion: SHIELD then UNSHIELD, verifying balances.
cmd_roundtrip() {
    require_confidential_enabled
    require_api_key
    check_coordinator
    echo -e "${CYAN}== Confidential round-trip: SHIELD → UNSHIELD ($SHIELD_AMOUNT $SHIELD_TOKEN) ==${NC}"

    # Prereq: public intents balance must cover the shield amount.
    local pub_bal; pub_bal=$(public_intents_balance "$SHIELD_TOKEN")
    echo "  public intents balance of $SHIELD_TOKEN: $pub_bal"
    if [ "$(bi_cmp "$pub_bal" "$SHIELD_AMOUNT")" = "-1" ]; then
        echo -e "  ${RED}FAIL${NC}: need ≥ $SHIELD_AMOUNT in public intents to shield. Fund first (see 'setup')."
        exit 1
    fi

    local cf_before; cf_before=$(cf_balance "$SHIELD_TOKEN")
    echo "  confidential balance before: $cf_before"

    echo -e "${CYAN}[1/4] SHIELD…${NC}"
    # Body built in a variable to dodge bash brace-expansion inside `$(...)` which
    # otherwise splits `{"a":"X","b":"Y"}` into two function calls.
    local shield_body; shield_body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/deposit" "$shield_body" "shield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "SHIELD"

    echo -e "${CYAN}[2/4] verify confidential balance increased by $SHIELD_AMOUNT…${NC}"
    local cf_mid expected_mid; cf_mid=$(cf_balance "$SHIELD_TOKEN"); expected_mid=$(bi_add "$cf_before" "$SHIELD_AMOUNT")
    echo "  confidential balance after shield: $cf_mid (expected $expected_mid)"
    if [ "$(bi_cmp "$cf_mid" "$expected_mid")" = "0" ]; then
        echo -e "  ${GREEN}PASS${NC} balance increased by the shielded amount"
    else
        echo -e "  ${YELLOW}WARN${NC} balance != before+amount (fees/rounding or solver timing); continuing"
    fi

    echo -e "${CYAN}[3/4] UNSHIELD…${NC}"
    local unshield_body; unshield_body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/unshield" "$unshield_body" "unshield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "UNSHIELD"

    echo -e "${CYAN}[4/4] verify confidential balance returned to baseline…${NC}"
    local cf_after; cf_after=$(cf_balance "$SHIELD_TOKEN")
    echo "  confidential balance after unshield: $cf_after (baseline $cf_before)"
    if [ "$(bi_cmp "$cf_after" "$cf_before")" = "0" ]; then
        echo -e "  ${GREEN}PASS${NC} round-trip complete — balance back to baseline"
    else
        echo -e "  ${YELLOW}WARN${NC} residual delta (fees/rounding/timing): after=$cf_after baseline=$cf_before"
    fi
    echo -e "${GREEN}round-trip OK${NC}"
}

cmd_shield() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== SHIELD $SHIELD_AMOUNT of $SHIELD_TOKEN ==${NC}"
    local body; body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/deposit" "$body" "shield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "SHIELD"
}

cmd_unshield() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== UNSHIELD $SHIELD_AMOUNT of $SHIELD_TOKEN ==${NC}"
    local body; body=$(printf '{"token":"%s","amount":"%s"}' "$SHIELD_TOKEN" "$SHIELD_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/unshield" "$body" "unshield-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "UNSHIELD"
}

cmd_balance() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== Confidential balances ==${NC}"
    parse_response "$(curl_get "/wallet/v1/confidential/balance")"
    echo -e "  HTTP $RESP_CODE"
    echo "  $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"
    [ "$RESP_CODE" = "200" ] || exit 1
}

cmd_deposit_intent() {
    require_confidential_enabled; require_api_key; check_coordinator
    echo -e "${CYAN}== Cross-chain DEPOSIT intent (quote only): $DEPOSIT_SOURCE_ASSET → confidential ==${NC}"
    local body; body=$(printf '{"source_asset":"%s","amount":"%s"}' "$DEPOSIT_SOURCE_ASSET" "$DEPOSIT_AMOUNT")
    parse_response "$(curl_post "/wallet/v1/confidential/deposit-intent" "$body")"
    echo -e "  HTTP $RESP_CODE"
    [ "$RESP_CODE" = "200" ] || { echo "  $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"; exit 1; }
    echo "  $(echo "$RESP_BODY" | jq -c '.')"
    echo -e "  ${CYAN}Send $DEPOSIT_AMOUNT to deposit_address on the source chain to fund your confidential balance.${NC}"
}

cmd_withdraw() {
    require_confidential_enabled; require_api_key; check_coordinator
    local chain="${WITHDRAW_CHAIN:-solana}"
    local to="${WITHDRAW_TO:?Set WITHDRAW_TO=<destination-chain address>}"
    local token="${WITHDRAW_TOKEN:-$SOL_USDC}"
    local amount="${WITHDRAW_AMOUNT:-$DEPOSIT_AMOUNT}"
    echo -e "${CYAN}== WITHDRAW $amount $token (confidential → $chain:$to) ==${NC}"
    local body="{\"chain\":\"$chain\",\"to\":\"$to\",\"amount\":\"$amount\",\"token\":\"$token\"}"
    echo -e "${CYAN}[1/2] dry-run…${NC}"
    parse_response "$(curl_post "/wallet/v1/confidential/withdraw/dry-run" "$body")"
    echo -e "  HTTP $RESP_CODE : $(echo "$RESP_BODY" | jq -c '.' 2>/dev/null || echo "$RESP_BODY")"
    echo -e "${CYAN}[2/2] real withdraw…${NC}"
    parse_response "$(curl_post "/wallet/v1/confidential/withdraw" "$body" "cwithdraw-$(date +%s)-$$")"
    report_op
    assert_settled "${LAST_REQUEST_ID:-}" "WITHDRAW"
}

cmd_status() {
    require_api_key
    local rid="${1:-${LAST_REQUEST_ID:-}}"
    [ -n "$rid" ] || { echo -e "${RED}Usage: $0 status <request_id>${NC}"; exit 1; }
    set +e; poll_request "$rid"; local rc=$?; set -e
    [ "$rc" = "1" ] && exit 1 || true
}

cmd_show() {
    echo "State file: $STATE_FILE"
    echo "WALLET_ID:    ${WALLET_ID:-<none>}"
    echo "NEAR_ADDRESS: ${NEAR_ADDRESS:-<none>}"
    echo "API key:      ${WALLET_API_KEY:0:10}${WALLET_API_KEY:+…}"
}

cmd_reset() {
    if [ -f "$STATE_FILE" ]; then rm -f "$STATE_FILE"; echo "Removed $STATE_FILE."; else echo "No saved state at $STATE_FILE."; fi
}

# ============================================================================
# Dispatch
# ============================================================================

CMD="${1:-}"; shift || true
case "$CMD" in
    setup)          cmd_setup ;;
    roundtrip)      cmd_roundtrip ;;
    shield)         cmd_shield ;;
    unshield)       cmd_unshield ;;
    balance)        cmd_balance ;;
    deposit-intent) cmd_deposit_intent ;;
    withdraw)       cmd_withdraw ;;
    status)         cmd_status "$@" ;;
    show)           cmd_show ;;
    reset)          cmd_reset ;;
    *)
        echo "Usage: $0 <command>"
        echo ""
        echo "  setup           — register/reuse wallet, show address + prerequisites"
        echo "  roundtrip       — SHIELD→UNSHIELD with balance assertions (the real-token test)"
        echo "  shield          — SHIELD 0.01 wNEAR (asserts settlement)"
        echo "  unshield        — UNSHIELD back (asserts settlement)"
        echo "  balance         — show confidential balances"
        echo "  deposit-intent  — cross-chain DEPOSIT quote (returns a bridge deposit address)"
        echo "  withdraw        — cross-chain WITHDRAW (needs WITHDRAW_TO; chain=near is rejected)"
        echo "  status <id>     — poll a request to terminal status"
        echo "  show / reset    — print / delete saved wallet state"
        echo ""
        echo "GATE: live phases require ONECLICK_CONFIDENTIAL_JWT set; unset → SKIP (exit 0)."
        echo "PREREQ (roundtrip/shield): SHIELD_TOKEN already in your PUBLIC intents balance."
        ;;
esac
