-- TEE session management for challenge-response worker authentication
-- Workers prove TEE identity by signing a challenge with their TEE-attested key,
-- which is then verified against the register-contract via NEAR RPC.

CREATE TABLE worker_tee_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash TEXT NOT NULL,
    worker_public_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_tee_sessions_token ON worker_tee_sessions(token_hash);
CREATE INDEX idx_tee_sessions_active ON worker_tee_sessions(is_active) WHERE is_active = TRUE;

-- One-time challenges for challenge-response protocol.
-- Challenge is generated by coordinator, signed by worker, then deleted.
CREATE TABLE tee_challenges (
    challenge TEXT PRIMARY KEY,
    token_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
